# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        square:
            quality: 75
            filters:
                thumbnail:
                    size: [400, 400]
                    mode: outbound
        mini:
            quality: 75
            filters:
                thumbnail:
                    size: [55, 55]
                    mode: outbound
        banniere:
            quality: 80
            filters:
                thumbnail:
                    size: [1000, 600]
                    mode: outbound